<?php
require "Employee.php";

class Support extends Employee {
    private $supportRole;
    private $roleStartDate;

    /**
     * Support constructor.
     * @param $firstName - parameter the same as Employee class
     * @param $lastName - parameter the same as Employee class
     * @param $gender - parameter the same as Employee class
     * @param $dateOfBirth - parameter the same as Employee class
     * @param $clinic - parameter the same as Employee class
     * @param $personalPhoneNumber - parameter the same as Employee class
     * @param $email - parameter the same as Employee class
     * @param $supportRole - takes a string value to represent the job role,eg. receptionist, intern
     * @throws Exception - throws exception if gender != 'male' or 'female'
     */
    public function __construct($firstName, $lastName, $gender, $dateOfBirth, $clinic, $personalPhoneNumber, $email, $supportRole) {
        parent::__construct($firstName, $lastName, $gender, $dateOfBirth, $clinic, $personalPhoneNumber, $email);
        $this->setSupportRole($supportRole);
        $this->roleStartDate = new DateTime("now");
    }

    /**
     * Method to get the value of the Support class instance start date value generated by the system upon instance creation.
     * @return mixed - returns a string format of the DateTime value of the system assigned roleStartDate attribute.
     */
    public function getRoleStartDate() {
        return $this->roleStartDate->format("Y-m-d");
    }

    /**
     * @return mixed - returns the string value for the supportRole attribute.
     */
    public function getSupportRole() {
        return $this->supportRole;
    }

    /**
     * Method to assign a string value to the supportRole attribute, method will cast parameter to string, lowercase
     * and capitalise the first char.
     * @param mixed $supportRole - takes a string value to assign to the supportRole attribute
     */
    public function setSupportRole($supportRole): void {
        $role = (string)$supportRole;
        $role = strtolower($role);
        $role = ucfirst($role);
        $this->supportRole = $role;
    }
}
//$rodney = new Support("rodney", "le blue", 'male', "1991-02-25", "sydney", "0444888777", "billy@gmail.com", "receptionist");
//
//print($rodney->getFirstName()) . "\n";
//print($rodney->getLastName()) . "\n";
//print($rodney->getGender()) . "\n";
//print($rodney->getDateOfBirth()) . "\n";
//print($rodney->getClinic()) . "\n";
//print($rodney->getPhoneNumber()) . "\n";
//print($rodney->getEmail()) . "\n";
//print($rodney->getHireDate()) . "\n";
//print($rodney->getDateOfResignation()) . "\n";
//print($rodney->getSupportRole()) . "\n";
