<?php
require "Employee.php";

class SystemAdmin extends Employee {
    private $adminRole;
    private $lastLoginDateTime;

    public function __construct($firstName, $lastName, $gender, $dateOfBirth, $clinic, $personalPhoneNumber, $email, $adminRole) {
        parent::__construct($firstName, $lastName, $gender, $dateOfBirth, $clinic, $personalPhoneNumber, $email);
        $this->setAdminRole($adminRole);
        $this->lastLoginDateTime = null;
    }

    /**
     * @return mixed - Returns the string value of the adminRole attribute for SystemAdmin instance
     */
    public function getAdminRole() {
        return $this->adminRole;
    }

    /**
     * @param mixed $roleString - Takes a String value for the name of the Admin role, strips string and capitalises first char.
     */
    public function setAdminRole($roleString): void {
        $roleString = (string)trim($roleString);
        $roleString = strtolower($roleString);
        $roleString = ucfirst($roleString);
        $this->adminRole = $roleString;
    }

    /**
     * @return mixed - returns DateTime string format of "YYYY-mm-dd HH:mm:ss of last login time by instance. If
     * user has never logged in will return a string stating instance has never logged in.
     */
    public function getLastLoginDateTime() {
        if ($this->lastLoginDateTime == null) {
            return "Never logged in";
        } else {
            return $this->lastLoginDateTime->format("Y-m-d H:i:s");
        }
    }

    /**
     * Method to record the last time a SystemAdmin user logged into the system, should only take a system generated
     * DateTime object.
     * @param mixed $lastLoginDateTime - Takes a DateTime object, should be generated by the system and not manually entered.
     */
    public function setLastLoginDateTime($lastLoginDateTime): void {
        $this->lastLoginDateTime = $lastLoginDateTime;
    }

    public function createEmployee() {
        // code to create a Employee in the SQL Database.
    }

    public function deleteEmployee() {
        // code to remove an SQL Employee entry.
    }

}

//$andy = new SystemAdmin("andy", "admin", "male", "1999-01-01", "Cairns", "0455111222", "this@hotmail.com", "Developer");
//print($andy->getFirstName()) . "\n";
//print($andy->getLastName()) . "\n";
//print($andy->getGender()) . "\n";
//print($andy->getDateOfBirth()) . "\n";
//print($andy->getClinic()) . "\n";
//print($andy->getPhoneNumber()) . "\n";
//print($andy->getEmail()) . "\n";
//print($andy->getHireDate()) . "\n";
//print($andy->getDateOfResignation()) . "\n";
//print($andy->getAdminRole()) . "\n";
//print($andy->getLastLoginDateTime()) . "\n";